consultaciudadanoApp/urls.py
from rest_framework.routers import DefaultRouter
from consultaciudadanoApp.views.apiciudadanoView import ciudadanosAPIviewSet

router_ciudadanos = DefaultRouter()

router_ciudadanos.register(prefix='ciudadanos', basename='ciudadanos', viewset = ciudadanosAPIviewSet)

consultaciudadanoProject/urls.py
from django.contrib import admin
from django.urls import path, include

from consultaciudadanoApp.urls import router_ciudadanos
from consultaciudadanoApp.views import pagPrincipalView
from consultaciudadanoApp.views import registro
from consultaciudadanoApp.views import mostrarCiudadanosView
from consultaciudadanoApp.views import pagCerrarSesionView
from consultaciudadanoApp.views import inicioSesionView
from consultaciudadanoApp.views import crearCiudadanosView
#from consultaciudadanoApp.views import actualizarCiudadanoView
from consultaciudadanoApp.views import buscarCiudadanoView
from consultaciudadanoApp.views import bienvenidaView
from consultaciudadanoApp.views import consultarUsuario
#from consultaciudadanoApp.views import generarPDF
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', pagPrincipalView.principal, name = "index"),
    path('bienvenida/', bienvenidaView.bienvenida, name = "bienvenida"),
    path('ciudadanos/', mostrarCiudadanosView.ciudadanos, name = "ciudadanos"),
    path('ciudadanos/crear/', crearCiudadanosView.crearCiudadanos, name = "crear_ciudadanos"),
    #path('ciudadanos/actualizar/<int:id_ciudadano>', actualizarCiudadanoView.actualizarCiudadanos, name = "actualizar_ciudadanos"),
    #path('ciudadanos/<int:id_ciudadano>/', mostrarCiudadanoView.mostrarCiudadanos, name = "mostrar_ciudadanos"),
    path('ciudadanos/buscar/', buscarCiudadanoView.buscarCiudadano, name = "ciudadanos_buscar"),
    path('buscar/Usuario/', consultarUsuario.buscarusuario, name = "ciudadanos_buscarusuario"),
    #ath('ciudadanos/generar/pdf/', generarListaView , name = "generar_pdf"),
    path('registro/', registro.ingresar, name = "registro"),
    path('iniciarsesion/',inicioSesionView.iniciarSesion , name = "iniciarsesion"),
    path('cerrarsesion/',pagCerrarSesionView.cerrar , name = "cerrarsesion"),
    #path('generarpdf/',generarPDF.generarPDF.as_view() , name = "generarpdf"),

    path('buscar/Usuario/cambiocontraseña/', auth_views.PasswordResetView.as_view(template_name="ingresarcorreo.html"), name = "password_reset"),
    path('mensaje/cambiocontraseña/',auth_views.PasswordResetDoneView.as_view(template_name="mensajeEnviocorreo.html") , name = "password_reset_done"),
    path('cambio/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="formcontraseña.html"), name = "password_reset_confirm"),
    path('cambio/verificado/', auth_views.PasswordResetCompleteView.as_view(template_name="cambioContraseña.html"), name = "password_reset_complete"),
    
    path('api/', include(router_ciudadanos.urls)),
]

consultaciudadanoApp/models/ciudadanos.py
from django.db import models

from .rh import Tiposangre
from .estado import Estado
from django.contrib.auth.models import User

class Ciudadanos(models.Model):
    idciudadano = models.AutoField(primary_key=True)
    identificacion = models.IntegerField(unique= True)
    nombres = models.TextField(max_length=100)
    apellidos = models.TextField(max_length=100)
    fechadenacimiento = models.DateField()
    lugardenacimiento = models.TextField(max_length=50)
    fechadeexpedicion = models.DateField()
    lugardeexpedicion = models.TextField(max_length=50)
    estatura = models.IntegerField()
    id_rh = models.ForeignKey(Tiposangre, null=True, on_delete = models.CASCADE)
    id_estado  = models.ForeignKey(Estado,  null=True, on_delete = models.CASCADE)
    usuario = models.ForeignKey(User, null=True, on_delete = models.CASCADE)


    def __str__(self):
        #return self.id_venta, self.cantidad
        return f'id: {self.idciudadano} identificacion: {self.identificacion}  nombres: {self.nombres} id: {self.id_estado}'
        

consultaciudadanoApp/models/estado.py
from django.db import models

class Estado(models.Model):
    id_estado= models.AutoField(primary_key=True)
    estado = models.TextField(max_length=50)
    descricion = models.TextField(max_length=100)

    def __str__(self):
        #return self.id_venta, self.cantidad
        #return f'id: {self.id_estado} Estado Ciudadano:{self.estado} descripcion: {self.descricion}'
        return f'{self.estado}'
        
        

consultaciudadanoApp/models/fuerza.py
from django.db import models

class Fuerza(models.Model):
    id_fuerza= models.AutoField(primary_key=True)
    fuerzapublica = models.TextField(max_length=100)

    def __str__(self):
        #return self.id_venta, self.cantidad
        return f'Fuerza Publica:{self.fuerzapublica}'

consultaciudadanoApp/models/personalfuerzap.py
from django.db import models
from .fuerza import Fuerza
from .rango import Rango


class Personalfp(models.Model):
    idpersonalfp = models.AutoField(primary_key=True)
    identificacion = models.IntegerField(default=0)
    nombres = models.TextField(max_length=100)
    apellidos = models.TextField(max_length=100)
    correoelectronico = models.TextField(max_length=60)
    id_fuerza  = models.ForeignKey(Fuerza,  on_delete = models.CASCADE)
    id_rango  = models.ForeignKey(Rango,  on_delete = models.CASCADE)

    def __str__(self):
        #return self.id_venta, self.cantidad
        return f'id: {self.idpersonalfp} identificacion: {self.identificacion}  nombres: {self.nombres} apellidos: {self.apellidos} correoelectrónico: {self.correoelectronico} fuerza: {self.id_fuerza} rango: {self.id_rango}'

consultaciudadanoApp/models/rango.py
from django.db import models

class Rango(models.Model):
    id_fuerza= models.AutoField(primary_key=True)
    fuerzapublica = models.TextField(max_length=100)

    def __str__(self):
        #return self.id_venta, self.cantidad
        return f'Fuerza Publicas:{self.fuerzapublica}'

consultaciudadanoApp/models/rh.py
from django.db import models

class Tiposangre(models.Model):
    id_rh = models.AutoField(primary_key=True)
    tipo_rh = models.TextField(max_length=10)

    def __str__(self):
        #return self.id_venta, self.cantidad
        return f'{self.tipo_rh}'

consultaciudadanoApp/models/usuario.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

from .fuerza import Fuerza
from .rango import Rango


#definir usuarios y superUsuarios
#class UsuarioManager(BaseUserManager):
#    def create_user(self, identificacion, email, username, nombres, apellidos,id_fuerza,id_rango, password=None):
#        if not email:
#            raise ValueError('El usuario no digito un correo')
#        usuario = self.model(
#            username= username,
#            identificacion=identificacion, 
#            email = self.normalize_email(email),
#            nombres= nombres,
#            apellidos= apellidos,
#            id_fuerza = id_fuerza,
#            id_rango = id_rango
#        )

#       usuario.set_password(password)
#        usuario.save()
#        return usuario

#    def create_superuser(self, identificacion, email, username, nombres, apellidos,id_fuerza,id_rango, password):
#        usuario = self.create_user(
#           username= username,
#            identificacion=identificacion, 
#            email=self.normalize_email(email),
#            nombres= nombres,
#            apellidos= apellidos,
#            id_fuerza = id_fuerza,
#            id_rango = id_rango
#        )
#        usuario.usuario_administrador = True
#        UsuarioNue.save()
#        return usuario


class usuario(AbstractBaseUser):
    usermane = models.CharField('Usuario',unique=True, max_length=100) 
    identificacion = models.IntegerField('Identificacion',unique=True)
    email= models.EmailField('Correo Electronico', max_length=100, unique= True)
    nombres = models.CharField('Nombres',max_length=150, blank=True, null= True)
    apellidos = models.CharField('Apellidos',max_length=150, blank=True, null= True)
    id_fuerza  = models.ForeignKey(Fuerza,  on_delete = models.CASCADE)
    id_rango  = models.ForeignKey(Rango,  on_delete = models.CASCADE)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [usermane, identificacion]

consultaciudadanoApp/views/actualizarCiudadanoView.py
from django.shortcuts import render, redirect, get_object_or_404
from consultaciudadanoApp.models import Ciudadanos
from consultaciudadanoApp.formularios import formCrearCiudadano
from django.contrib.auth.decorators import login_required

@login_required
def actualizarCiudadanos(request , id_ciudadano ):
    
    if request.method == 'GET':
        #ciudadano = Ciudadanos.objects.get(pk= id_ciudadano)
        ciudadano = get_object_or_404(Ciudadanos, pk= id_ciudadano)
        form = formCrearCiudadano(instance= ciudadano)
        return render(request,'mostrar_ciudadano.html', {'ciudadano': ciudadano})
    else:
        try:
            #ciudadano = Ciudadanos.objects.get(pk= id_ciudadano)
            ciudadano = get_object_or_404(Ciudadanos, pk= id_ciudadano, user=request.user)
            form = formCrearCiudadano(request.POST, instance= ciudadano)
            form.save()
            redirect('ciudadanos')
        except:
            return render(request,'mostrar_ciudadano.html', {'ciudadano': ciudadano, 'form': form,
            'error': 'error al actualizar la tarea'
            })

consultaciudadanoApp/views/apiciudadanoView.py
from rest_framework.viewsets import ModelViewSet

from consultaciudadanoApp.models import Ciudadanos
from consultaciudadanoApp.serializers import ciudadanosSerializer

class ciudadanosAPIviewSet(ModelViewSet):
    serializer_class = ciudadanosSerializer
    queryset = Ciudadanos.objects.all()

consultaciudadanoApp/views/bienvenidaView.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def bienvenida(request):
    
    return render(request, 'bienvenida.html')

consultaciudadanoApp/views/buscarCiudadanoView.py
from django.shortcuts import render, get_object_or_404
from consultaciudadanoApp.models import Ciudadanos
from django.contrib.auth.decorators import login_required


@login_required
def buscarCiudadano(request ):
    if request.method == 'GET':
        
        return render(request, 'buscarCiudadano.html')
    else:
        if request.POST['identificacion1'] == request.POST['identificacion2']:
        
                id_ciudadano = request.POST.get("identificacion1")
                #print(id_ciudadano)
                ciudadano = Ciudadanos.objects.get(identificacion= id_ciudadano)
                ciudadano = get_object_or_404(Ciudadanos, identificacion= id_ciudadano)
                
                return render(request,'mostrar_ciudadano.html', {'ciudadano': ciudadano})
                
        else:
                return render(request, 'buscarCiudadano.html',{
                    
                    "error": 'Los documentos digitados no son iguales'
                })     

consultaciudadanoApp/views/consultarUsuario.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User

def buscarusuario(request ):
    if request.method == 'GET':
        
        return render(request, 'buscarUsuario.html')
    else:
        if request.POST['username1'] == request.POST['username2']:
        
                id_usuario = request.POST.get("username1")
                #print(id_usuario)
                usuario = User.objects.get(username= id_usuario)
                usuario = get_object_or_404(User, username= id_usuario)
                
                return render(request,'ingresarcorreo.html', {'ciudadano': usuario})
                
        else:
                return render(request, 'buscarUsuario.html',{
                    
                    "error": 'Los documentos digitados no son iguales'
                })     

consultaciudadanoApp/views/crearCiudadanosView.py
from django.shortcuts import render, redirect
from consultaciudadanoApp.formularios.formCrearCiudadano import CiudadanoFrom
from django.contrib.auth.decorators import login_required

@login_required
def crearCiudadanos(request):
    
    if request.method == 'GET':
        return render(request,'crear_ciudadanos.html',{
            'form': CiudadanoFrom
    })
    else:
        try:

            form = CiudadanoFrom(request.POST)
            nuevoCiudadano = form.save(commit = False)
            nuevoCiudadano.user = request.user
            #print(nuevoCiudadano)
            nuevoCiudadano.save()
            return redirect('ciudadanos')
        except ValueError:
            return render(request,'crear_ciudadanos.html',{
            'form': CiudadanoFrom,
            'error': 'Digite toda la información'
    })

consultaciudadanoApp/views/inicioSesionView.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login

def iniciarSesion(request):

    if request.method == 'GET':
        #print('enviado formulario')
        return render(request, 'iniciosesion.html',{
        'from': AuthenticationForm
    })
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        
        if user is None:
            return render(request, 'iniciosesion.html',{
            'from': AuthenticationForm,
            'error': 'El usuario no se encuentra Registrado!!'
        })
        else:
            login(request, user)
            return redirect('bienvenida')

consultaciudadanoApp/views/mostrarCiudadanosView.py
from django.shortcuts import render
from consultaciudadanoApp.models import Ciudadanos
from django.contrib.auth.decorators import login_required

@login_required
def ciudadanos(request):
    ciudadanos = Ciudadanos.objects.all()

    return render(request, 'ciudadanos.html', {'ciudadanos': ciudadanos })

consultaciudadanoApp/views/pagCerrarSesionView.py
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

@login_required
def cerrar(request):
    logout(request)
    return redirect('index')

consultaciudadanoApp/views/pagPrincipalView.py
from django.shortcuts import render

def principal(request):
    return render(request, 'index.html')

consultaciudadanoApp/views/pdf.py
#from django.shortcuts import HttpResponse
#from django.views import View
#from consultaciudadanoApp.models import Ciudadanos

#import os
#from django.conf import settings
#from django.http import HttpResponse
#from django.template.loader import get_template
#from xhtml2pdf import pisa
#from django.contrib.staticfiles import finders

#class generarPDF(View):
#    def get(self, *args, **kwargs):
        
#        template = get_template('ciudadanos.html')
#        context = {
#            'ciudadanos': Ciudadanos.objects.all(),
            
#            }
#        html = template.render(context)
#        response = HttpResponse(content_type='application/pdf')
#        #response['Content-Disposition'] = 'attachment; filename="reporte.pdf"'
#        pisa_status = pisa.CreatePDF(html, dest=response)
#        if pisa_status.err:
#            return HttpResponse('err' + html + '</pre>')
#        return response

consultaciudadanoApp/views/registro.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django.contrib.auth import login
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required

@login_required



def ingresar(request):

    if request.method == 'GET':
        #print('enviado formulario')
        return render(request, 'registro.html',{
            'from': UserCreationForm
    })
    else:
        #print('obteniendo datos')
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password2'], email=request.POST['email'], first_name = request.POST['first_name'], last_name = request.POST['last_name'])
                user.save()
                login(request, user)
                return redirect('bienvenida')
                #return HttpResponse('usuario creado satisfactoriamente')
            except IntegrityError:
                return render(request, 'registro.html',{
                    'from': UserCreationForm,
                    "error": 'el usuario ya existe'
                })

        return render(request, 'registro.html',{
                    'from': UserCreationForm,
                    "error": 'las contraseñas no son iguales'
                }) 
        

consultaciudadanoApp/templates/actualizarCiudadanos.html
{% extends 'base.html' %}

{% block content %}
<h1>actualizar Ciudadanos</h1>

<form method="POST">
    
    {{error}}
    
    {% csrf_token %}
    
    {{form.as_p}}

    <button>
        Crear
    </button>
{% endblock %}

consultaciudadanoApp/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registraduria Konrad</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js">
    
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/home">ER</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/home">Inicio</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/ciudadanos">Ver Ciudadanos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ciudadanos/crear">Crear Ciudadanos </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/ciudadanos/buscar">Buscar Ciudadano</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/cerrarsesion">Cerrar Sesión</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="/iniciarsesion">Iniciar Sesión</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/buscar/Usuario/">Buscar Usuario</a>
                </li>
                {% endif %}
            </ul>
        </div>
        </div>
    </nav>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script>
        $('.navbar-nav>li>a').on('click', function(){
            $('.navbar-collapse').collapse('hide');
        });
    </script>
    

    
    {% block content %}    
    {% endblock %}
</body>
<div class="container ">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2022 Edwin Ramírez</span>
        </div>

    </footer>
</div>
</html>

consultaciudadanoApp/templates/crear_ciudadanos.html
{% extends 'base.html' %}

{% block content %}

<main class="container py-5">
    <div>
        <form action="/ciudadanos/crear/" method="POST" class="card card-body needs-validation" novalidate>
            
            <h1 class="display-1 text-center">Registrar ciudadanos</h1>
            
            {{error}}
            {% csrf_token %}
            
            <div class="mb-3" >
                <label for="id_identificacion">Identificación:</label>
                <input type="number" name="identificacion" id="id_identificacion" class="form-control" placeholder="Documento de identidad"  required>
                <div class="invalid-feedback">
                    Proporciona una identificación valida.
                </div>
            </div>
            
            
            <div class="mb-3">
                <label for="id_nombres">Nombres:</label>
                <textarea name="nombres" id="id_nombres" class="form-control"cols="1" rows="1" class="form-control "  placeholder="Digite su nombre" required></textarea>
                <div class="invalid-feedback">
                    Digite un Nombre valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_apellidos">Apellidos:</label>
                <textarea cols="1" rows="1" name="apellidos" id="id_apellidos" class="form-control" class="form-control "  placeholder="Ingrese sus apellidos" required></textarea>
                <div class="invalid-feedback">
                    Digite un Apellido valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_fechadenacimiento">Fecha de Nacimiento:</label>
                <input type="date" name="fechadenacimiento" id="id_fechadenacimiento" class="form-control" required>
                <div class="invalid-feedback">
                    Digite una fecha valida.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_lugardenacimiento">Lugar de Nacimiento:</label>
                <textarea cols="1" rows="1" name="lugardenacimiento" id="id_lugardenacimiento" class="form-control" placeholder="Ingrese su lugar de nacimiento" class="form-control " required></textarea>
                <div class="invalid-feedback">
                    Digite un lugar de nacimiento valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_fechadeexpedicion">Fecha de expedición:</label>
                <input type="date" name="fechadeexpedicion" id="id_fechadeexpedicion" class="form-control" required>
                <div class="invalid-feedback">
                    Digite una fecha valida.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_lugardeexpedicion">Lugar de expedición:</label>
                <textarea cols="1" rows="1" name="lugardeexpedicion" id="id_lugardeexpedicion" class="form-control" placeholder="Ingrese el lugar de expedición del documento" class="form-control " required></textarea>
                <div class="invalid-feedback">
                    Digite una fecha de expedición valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_estatura">Estatura:</label>
                <input type="number" name="estatura" id="id_estatura" class="form-control" placeholder="Digite su estatura" required>
                <div class="invalid-feedback">
                    Digite una estatura valida.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_id_rh" required>Tipo de sangre:</label>
                <select class="form-select" required name="id_rh" id="id_id_rh" class="form-control is-invalid" >
                    <option value="" selected="">---------</option>
                    <option value="1">Tipo Sangre: O+</option>
                    <option value="2">Tipo Sangre: O-</option>
                    <option value="3">Tipo Sangre: A+</option>
                    <option value="4">Tipo Sangre: A-</option>
                    <option value="5">Tipo Sangre: B+</option>
                    <option value="6">Tipo Sangre: B-</option>
                    <option value="7">Tipo Sangre: AB+</option>
                    <option value="8">Tipo Sangre: AB-</option>
                </select>
                <div class="invalid-feedback">
                    Seleccione un tipo de sagre valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="id_id_estado">Estado:</label>
                <select class="form-select" required name="id_estado" id="id_id_estado" >
                    <option value="" selected="">---------</option>
                    <option value="1">Requerido</option>
                    <option value="2">No Requerido</option>
                </select>
                <div class="invalid-feedback" >
                    Seleccione un Estado valido.
                </div>
            </div>
            
            <button class="btn btn-dark">
                Crear
            </button>
        </form>
    </div>    
    
</main>


<SCript>
    // Ejemplo de JavaScript inicial para deshabilitar el envío de formularios si hay campos no válidos
    (function () {
        'use strict'
    
      // Obtener todos los formularios a los que queremos aplicar estilos de validación de Bootstrap personalizados
        var forms = document.querySelectorAll('.needs-validation')
    
      // Bucle sobre ellos y evitar el envío
        Array.prototype.slice.call(forms)
        .forEach(function (form) {
            form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
            }
    
            form.classList.add('was-validated')
            }, false)
        })
    })()
    
    </SCript>

<!-- formulario sin CSS 

<form action="/ciudadanos/crear/" method="POST">
    
    {{error}}
    
    {% csrf_token %}
    
    {{form.as_p}}

    <button>
        Crear
    </button>
-->
{% endblock %}

consultaciudadanoApp/templates/registro.html
{% extends 'base.html' %}

{% block content %}

<main class="container py-5">
    <div>
        <form action="/registro/" method="POST" class="card card-body  needs-validation" novalidate>
    
            <h1 class="display-1 text-center">Registrarse</h1>
            
            
            {{error}}
                        
            {% csrf_token %}

            <div class="mb-3">
                <label for="usermane">Identificación:</label>
                <input type="number" name="username" id="username" class="form-control" placeholder="identificación" required>
                <div class="invalid-feedback">
                    Proporciona una identificación valida.
                </div>
            </div>

            <div class="mb-3">
                <label for="first_name">Nombre:</label>
                <input type="text" name="first_name" id="first_name" class="form-control" placeholder="Ingrese su nombre" required>
                <div class="invalid-feedback">
                    Proporciona un nombre valido.
                </div>
            </div>

            <div class="mb-3">
                <label for="last_name">Apellidos:</label>
                <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Ingrese sus apellidos"required>
                <div class="invalid-feedback">
                    Proporciona apellidos validos.
                </div>
            </div>
            
            <div class="mb-3">
                <label for="id_id_estado">Fuerza Publica:</label>
                <select class="form-select" required name="id_estado" id="id_id_estado" >
                    <option value="" selected="">---------</option>
                    <option value="1">Policía</option>
                    <option value="2">Ejército</option>
                    <option value="3">Armada</option>
                    <option value="4">Fuerza Aérea</option>
                </select>
                
                <div class="invalid-feedback">
                    Proporciona una fuerza militar valida.
                </div>
            </div>

            <div class="mb-3">
                <label for="id_id_estado">Fuerza Publica:</label>
                <select class="form-select" required name="id_estado" id="id_id_estado" >
                    <option value="" selected="">---------</option>
                    <option value="1">Teniente</option>
                    <option value="2">Capitán</option>
                    <option value="3">Mayor</option>
                    <option value="4">Teniente coronel</option>
                    <option value="5">Coronel</option>
                </select>
                <div class="invalid-feedback" >
                    Seleccione un rango valido.
                </div>
            </div>

            <div class="mb-3">
                <label for="email">Correo Electronico:</label>
                <input type="email" name="email" id="id_email" class="form-control" placeholder="correo@fuerzamilitar.org" required>
                <div class="invalid-feedback">
                    Proporciona un correo electronico valido.
                </div>
            </div>
            <div class="mb-3">
                <label for="password1">Contraseña:</label>
                <input type="password" name="password1" id="password1" class="form-control" placeholder="Ingrese su contraseña" required>
                <div class="invalid-feedback">
                    Proporciona una contraseña valida.
                </div>
            </div>
            <div class="mb-3">
                <label for="password2">Confirme su contraseña:</label>
                <input type="password" name="password2" id="password2" class="form-control" placeholder="Ingrese nuevamente su contraseña" required>
                <div class="invalid-feedback">
                    Proporciona una contraseña valida.
                </div>
            </div>
            
            
            
            
            <button class="btn btn-dark">
                Registrarse
            </button>
        </form>
    </div>    

<script>
        // Ejemplo de JavaScript inicial para deshabilitar el envío de formularios si hay campos no válidos
        (function () {
            'use strict'
        
          // Obtener todos los formularios a los que queremos aplicar estilos de validación de Bootstrap personalizados
            var forms = document.querySelectorAll('.needs-validation')
        
          // Bucle sobre ellos y evitar el envío
            Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault()
                    event.stopPropagation()
                }
        
                form.classList.add('was-validated')
                }, false)
            })
        })()
        
</script>

</main>


{% endblock %}